### ISSUE TITLE
about wgdi -ks

### ISSUE THREAD

**Issue by wtyanxu** [SunPengChuan/wgdi-doc#2]
When I run ks, I get this error.
My computer always run the follow code:
Can't open prot.aln at D:\bin\pal2nal.v14\pal2nal.pl line 365.
I can not solve it

**Comment by SunPengChuan** [comment]
Can you provide these files? Or you delete this file in the current directory and run it again.

**Comment by wtyanxu** [comment]
[pal2nal.zip](https://github.com/SunPengChuan/wgdi-doc/files/9155730/pal2nal.zip)
Hi!That's the file.
If I delete this file, perl will show that the file cannot be found.
And only the first two columns of data in ks can be calculated.

**Comment by SunPengChuan** [comment]
The target of Ks calculation is the gene pair. I'm concerned it's a problem with your input data. Are you using the collinearity file?

**Comment by wtyanxu** [comment]
Thanks a lot for your help!
Yes, I've used the collinearity file.
The follow is my file.
[Egl.collinearity.zip](https://github.com/SunPengChuan/wgdi-doc/files/9167901/Egl.collinearity.zip)
[Egl.pep.zip](https://github.com/SunPengChuan/wgdi-doc/files/9167863/Egl.pep.zip)
[Egl.cds.zip](https://github.com/SunPengChuan/wgdi-doc/files/9167849/Egl.cds.zip)

**Comment by SunPengChuan** [comment]
I'm very sorry, this is a bug in wgdi 0.5.7.  I provided the new version and it fixed it.

**Comment by wtyanxu** [comment]
Thank you very much,I solved this problem.
